import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@/fsd/app/css/globals.css";
import { cn } from "@/fsd/shared/lib/utils";
import { ThemeProvider } from "@/fsd/app/providers/theme-provider";
import localFont from 'next/font/local'
import { Toaster } from "sonner";

const MtsWide = localFont({
  src: './MTSWide-Medium.woff2',
  variable: '--font-mtswide-sans',
  display: 'swap',
})

const MtsCompact = localFont({
  src: './MTSCompact-Medium.woff2',
  variable: '--font-mtscompact',
  display: 'swap',
})

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", MtsWide.className, MtsCompact.className, "font-sans")}
    >
      <body className="min-h-full flex flex-col">
          <ThemeProvider>
            {children}
            <Toaster
              position="bottom-center"
              toastOptions={{
                className: "rounded-md border bg-background text-foreground shadow-lg",
              }}
            />
          </ThemeProvider>
        </body>
    </html>
  );
}
